name: trend_setters_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - flask
      - pandas
      - langchain       
      - qdrant-client    
      - huggingface-hub   
      - accelerate==0.21.0         
      - transformers==4.56.1       
      - bitsandbytes==0.40.0    
      - langchain-huggingface        
      - sentence-transformers==2.2.2
